# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shell\
$jobs\
$sudo\
$username\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character\
"""

right_format = """
$kubernetes\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$dart\
$deno\
$golang\
$haskell\
$helm\
$java\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$python\
$ruby\
$rust\
$solidity\
$swift\
$terraform\
$zig\
$memory_usage\
$custom\
$status\
$os\
$battery\
$time\
"""

# Left prompt
[fill]
symbol = ' '

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[cmd_duration]
format = "[◄ $duration ](italic white)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = true

[directory]
home_symbol = "~"
read_only = " r-only"
use_os_path_sep = true
style = "italic"
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'bold #DA627D'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = " [$symbol $branch ]($style)"
symbol = ""
style = "#FCA17D"

[git_status]
style = "bold"
format = "([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed ]($style))"
conflicted = "[!!](italic bright-magenta)"
ahead = "[▴ [${count}](bold white)│](italic green)"
behind = "[▿ [${count}](bold white)│](italic red)"
diverged = "[◇ ▴[${ahead_count}](regular white)│▿[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[ ${count} ](italic bright-yellow)"
stashed = "[](italic white)"
modified = "[+ ${count} ](italic yellow)"
staged = "[ [$count](bold white) ](italic bright-cyan)"
renamed = "[󰑕](italic bright-blue)"
deleted = "[✕](italic red)"

[character]
format = "$symbol "
success_symbol = "[>](bold bright-blue)"
error_symbol = "[○](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"


# Right prompt

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"

[package]
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed yellow italic bold"

[c]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"

[dart]
symbol = "◁◅ "
format = " dart [$symbol($version )]($style)"

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[golang]
symbol = "∩ "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = "❯λ " 
format = " hs [$symbol($version )]($style)"

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow"

[nim]
symbol = "▴▲▴ "
format = " nim [$symbol($version )]($style)"

[nodejs]
format = " [node](italic) [($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock", "bun.lockb", "pnpm-lock.yaml"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "[⌉](bold bright-blue)⌊ "
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "◆ "
version_format = "${raw}"
style = "bold red"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "⊃ "
version_format = "${raw}"
style = "bold red"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "◁ "
style = "bold bright-red"
version_format = "${raw}"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"

[battery]
format = "[ $percentage]($style)"
# charging_symbol = "[↑](italic bold green)"
# discharging_symbol = "[↓](italic bold red)"
# full_symbol = "█"
# unknown_symbol = "░"
# empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed yellow"

[[battery.display]]
threshold = 70
style = "italic dimmed green"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%T"
utc_time_offset = "local"
style = "italic dimmed white"
